Repository AdobeDocs/creative-cloud-libraries, pull requests merged in 2020-10, with the labels that each got.

#3 Update version
  package-lock.json
  package.json
Labels: deploy, deploy:dev

#4 Update Summary default background
  src/pages/index.md
Labels: deploy, deploy:dev

#5 Add docs path
  gatsby-config.js
Labels: deploy, deploy:dev

#6 Max updates
  src/pages/images/frontify.png
  src/pages/images/holabrief.svg
  src/pages/index.md
Labels: deploy:dev

#7 Update index.md
  src/pages/index.md
Labels: deploy, deploy:dev

#8 Copy edits.
  src/pages/images/cc-hero.png
  src/pages/index.md
Labels: deploy, deploy:dev

#9 Forum CTA.
  src/pages/index.md
Labels: deploy, deploy:dev

#10 Partner list
  src/pages/images/google.png
  src/pages/index.md
Labels: deploy:dev

#11 More tweaks
  src/pages/images/frontify.png
  src/pages/images/holabrief.svg
  src/pages/images/streamline.png
  src/pages/images/tiled.png
  src/pages/index.md
Labels: deploy:dev

#13 Version bump.
  package.json
  src/pages/index.md
Labels: deploy, deploy:dev

#14 MAX release updates
  src/pages/index.md
Labels: deploy, deploy:dev

#19 Update dependency
  package-lock.json
  package.json
Labels: dependencies, deploy, deploy:dev
